# Generated by Django 4.2.6 on 2023-10-12 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replay_comment_related', to='Accounts.postcomment'),
        ),
    ]
