# Generated by Django 4.2.6 on 2023-10-13 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_is_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_follow_related', to=settings.AUTH_USER_MODEL)),
                ('user_is_followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_followed_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
